export const MIN_CONTENT_WIDTH_NUMBER = 360
export const MIN_CONTENT_WIDTH_PX_UNIT = `${MIN_CONTENT_WIDTH_NUMBER}px`

export const MAX_CONTENT_WIDTH_NUMBER = 768
export const MAX_CONTENT_WIDTH_PX_UNIT = `${MAX_CONTENT_WIDTH_NUMBER}px`
